# Generated by Django 4.2.4 on 2023-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_crmserviceinfo_oldexternalintegration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivyuser',
            name='isdisabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
