# Generated by Django 4.2.4 on 2023-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_alter_arrivyuser_isdisabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivyuser',
            name='isCompany',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='arrivyuser',
            name='sso_only',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
