# Generated by Django 4.2.4 on 2023-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0007_arrivyuser_settings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivyuser',
            name='settings_user',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
