# Generated by Django 4.2.4 on 2023-08-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0008_alter_arrivyuser_settings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_id',
            field=models.IntegerField(default=1),
        ),
    ]
