# Generated by Django 4.2.4 on 2023-08-21 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0009_alter_userprofile_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_fields', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('can_turnoff_location', models.BooleanField(default=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('notifications', models.JSONField()),
                ('skill_ids', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_status_priority_notifications_disabled', models.BooleanField(default=False)),
                ('invite_status', models.IntegerField(choices=[(7001, 'Pending'), (7002, 'Accepted]')], default=7001)),
                ('joined_datetime', models.DateTimeField()),
                ('additional_group_ids', models.IntegerField(blank=True, null=True)),
                ('allow_status_notifications', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('external_type', models.CharField(blank=True, max_length=100, null=True)),
                ('can_view_customers_of_all_groups', models.BooleanField(default=True)),
                ('active_task_id', models.IntegerField(blank=True, null=True)),
                ('allow_login_in_kiosk_mode_only', models.BooleanField(default=False)),
                ('is_included_in_billing', models.BooleanField(default=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('exact_location', models.CharField(blank=True, max_length=100, null=True)),
                ('use_lat_lng_address', models.BooleanField(default=False)),
                ('complete_address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_address_geo_coded', models.BooleanField()),
                ('user_type', models.IntegerField(choices=[(1000, 'Customer'), (1002, 'Crew')], default=1002)),
                ('entity_customer_id', models.IntegerField()),
                ('visible_bookings', models.IntegerField()),
                ('okta_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
