# Generated by Django 4.2.4 on 2023-08-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0012_customintegrationinfo_qrsettingsinfo_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_company_id', models.IntegerField()),
                ('company_entity_id', models.IntegerField()),
                ('is_disabled', models.BooleanField(default=False)),
                ('signup_channel', models.IntegerField(choices=[(3001, 'Email'), (3002, 'SMS'), (30003, 'Username')], default=3001)),
                ('signup_address', models.CharField(max_length=100)),
                ('signup_channel_2', models.IntegerField(choices=[(3001, 'Email'), (3002, 'SMS'), (30003, 'Username')], default=3001)),
                ('signup_address_2', models.CharField(max_length=100)),
                ('is_disable', models.BooleanField(default=False)),
                ('user_type', models.IntegerField(choices=[(1000, 'Customer'), (1002, 'Crew')], default=1002)),
            ],
        ),
        migrations.CreateModel(
            name='EntityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency', models.CharField(blank=True, max_length=100, null=True)),
                ('exact_location', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('image_id', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.CharField(blank=True, max_length=100, null=True)),
                ('acquisition_source', models.CharField(blank=True, max_length=100, null=True)),
                ('company_entity_id', models.IntegerField()),
                ('owned_company_id', models.IntegerField()),
                ('mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('social_links', models.JSONField()),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('is_on_boarding_guide_visited', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_companies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signups.usercompany')),
            ],
        ),
    ]
