# Generated by Django 4.2.4 on 2023-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0014_arrivyuser_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('social_links', models.JSONField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('exact_location', models.CharField(blank=True, max_length=100, null=True)),
                ('use_lat_lng_address', models.BooleanField(default=False)),
                ('complete_address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_address_geo_coded', models.BooleanField()),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency', models.CharField(blank=True, max_length=100, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_fields', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_implicit', models.BooleanField(default=False)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_addresses', models.JSONField()),
                ('default_locale', models.CharField(blank=True, max_length=100, null=True)),
                ('locale_date_format', models.CharField(blank=True, max_length=100, null=True)),
                ('locale_time_format', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
