# Generated by Django 4.2.4 on 2023-08-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0015_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='company_entity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.entity'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='owned_company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
