# Generated by Django 4.2.4 on 2023-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0016_alter_usercompany_company_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
