# Generated by Django 4.2.4 on 2023-08-24 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0019_alter_userprofile_crm_services_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='default_entity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signups.entity'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entityprofile',
            name='company_entity_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.entity')),
        ),
        migrations.AlterField(
            model_name='entityprofile',
            name='owned_company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
        migrations.AlterField(
            model_name='entityprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_entity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_entity', to='signups.entity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_entity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_entity', to='signups.entity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owned_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
