# Generated by Django 4.2.4 on 2023-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0022_alter_companyprofile_additional_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='sms_consent_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
