# Generated by Django 4.2.4 on 2023-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0023_alter_companyprofile_sms_consent_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='team_confirmation_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
