# Generated by Django 4.2.4 on 2023-08-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0024_alter_companyprofile_team_confirmation_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='exceptions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='rating_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
