# Generated by Django 4.2.4 on 2023-08-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0025_alter_companyprofile_exceptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='crm_services_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signups.crmserviceinfo'),
        ),
    ]
