# Generated by Django 4.2.4 on 2023-08-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0026_alter_companyprofile_crm_services_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='custom_integrations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signups.customintegrationinfo'),
        ),
    ]
